package detox.main;

import detox.BlockCommand;
import detox.BlockMove;
import org.bukkit.Material;
import org.bukkit.command.CommandExecutor;
import org.bukkit.plugin.java.JavaPlugin;

public class BlockShuffle extends JavaPlugin
{
    public static BlockShuffle instance;

    @Override
    public void onEnable()
    {
        instance = this;
        getLogger().info("Registering events and commands...");
        this.getServer().getPluginManager().registerEvents(new BlockMove(), this);
        this.getCommand("block").setExecutor((CommandExecutor) new BlockCommand());
        getLogger().info("Adding blocks to HashSet...");
        BlockCommand.allBlocks.add(Material.ANDESITE);
        BlockCommand.allBlocks.add(Material.GRANITE);
        BlockCommand.allBlocks.add(Material.DIORITE);
        BlockCommand.allBlocks.add(Material.STONE);
        BlockCommand.allBlocks.add(Material.COBBLESTONE);
        BlockCommand.allBlocks.add(Material.POLISHED_ANDESITE);
        BlockCommand.allBlocks.add(Material.POLISHED_DIORITE);
        BlockCommand.allBlocks.add(Material.POLISHED_GRANITE);
        BlockCommand.allBlocks.add(Material.GRASS_BLOCK);
        BlockCommand.allBlocks.add(Material.DIRT);
        BlockCommand.allBlocks.add(Material.BEDROCK);
        BlockCommand.allBlocks.add(Material.OAK_PLANKS);
        BlockCommand.allBlocks.add(Material.SPRUCE_PLANKS);
        BlockCommand.allBlocks.add(Material.BIRCH_PLANKS);
        BlockCommand.allBlocks.add(Material.JUNGLE_PLANKS);
        BlockCommand.allBlocks.add(Material.ACACIA_PLANKS);
        BlockCommand.allBlocks.add(Material.DARK_OAK_PLANKS);
        BlockCommand.allBlocks.add(Material.SAND);
        BlockCommand.allBlocks.add(Material.GRAVEL);
        BlockCommand.allBlocks.add(Material.GOLD_ORE);
        BlockCommand.allBlocks.add(Material.IRON_ORE);
        BlockCommand.allBlocks.add(Material.COAL_ORE);
        BlockCommand.allBlocks.add(Material.COAL_BLOCK);
        BlockCommand.allBlocks.add(Material.OAK_LOG);
        BlockCommand.allBlocks.add(Material.SPRUCE_LOG);
        BlockCommand.allBlocks.add(Material.BIRCH_LOG);
        BlockCommand.allBlocks.add(Material.JUNGLE_LOG);
        BlockCommand.allBlocks.add(Material.ACACIA_LOG);
        BlockCommand.allBlocks.add(Material.DARK_OAK_LOG);
        BlockCommand.allBlocks.add(Material.STRIPPED_OAK_LOG);
        BlockCommand.allBlocks.add(Material.STRIPPED_SPRUCE_LOG);
        BlockCommand.allBlocks.add(Material.STRIPPED_BIRCH_LOG);
        BlockCommand.allBlocks.add(Material.STRIPPED_JUNGLE_LOG);
        BlockCommand.allBlocks.add(Material.STRIPPED_ACACIA_LOG);
        BlockCommand.allBlocks.add(Material.STRIPPED_DARK_OAK_LOG);
        BlockCommand.allBlocks.add(Material.STRIPPED_OAK_WOOD);
        BlockCommand.allBlocks.add(Material.STRIPPED_SPRUCE_WOOD);
        BlockCommand.allBlocks.add(Material.STRIPPED_BIRCH_WOOD);
        BlockCommand.allBlocks.add(Material.STRIPPED_JUNGLE_WOOD);
        BlockCommand.allBlocks.add(Material.STRIPPED_ACACIA_WOOD);
        BlockCommand.allBlocks.add(Material.STRIPPED_DARK_OAK_WOOD);
        BlockCommand.allBlocks.add(Material.OAK_WOOD);
        BlockCommand.allBlocks.add(Material.SPRUCE_WOOD);
        BlockCommand.allBlocks.add(Material.BIRCH_WOOD);
        BlockCommand.allBlocks.add(Material.JUNGLE_WOOD);
        BlockCommand.allBlocks.add(Material.ACACIA_WOOD);
        BlockCommand.allBlocks.add(Material.DARK_OAK_WOOD);
        BlockCommand.allBlocks.add(Material.OAK_LEAVES);
        BlockCommand.allBlocks.add(Material.SPRUCE_LEAVES);
        BlockCommand.allBlocks.add(Material.BIRCH_LEAVES);
        BlockCommand.allBlocks.add(Material.JUNGLE_LEAVES);
        BlockCommand.allBlocks.add(Material.ACACIA_LEAVES);
        BlockCommand.allBlocks.add(Material.GLASS);
        BlockCommand.allBlocks.add(Material.LAPIS_ORE);
        BlockCommand.allBlocks.add(Material.DISPENSER);
        BlockCommand.allBlocks.add(Material.SANDSTONE);
        BlockCommand.allBlocks.add(Material.NOTE_BLOCK);
        BlockCommand.allBlocks.add(Material.CHISELED_SANDSTONE);
        BlockCommand.allBlocks.add(Material.CUT_SANDSTONE);
        BlockCommand.allBlocks.add(Material.GRASS);
        BlockCommand.allBlocks.add(Material.FERN);
        BlockCommand.allBlocks.add(Material.DEAD_BUSH);
        BlockCommand.allBlocks.add(Material.SEAGRASS);
        BlockCommand.allBlocks.add(Material.PISTON);
        BlockCommand.allBlocks.add(Material.WHITE_WOOL);
        BlockCommand.allBlocks.add(Material.ORANGE_WOOL);
        BlockCommand.allBlocks.add(Material.MAGENTA_WOOL);
        BlockCommand.allBlocks.add(Material.LIGHT_BLUE_WOOL);
        BlockCommand.allBlocks.add(Material.YELLOW_WOOL);
        BlockCommand.allBlocks.add(Material.LIME_WOOL);
        BlockCommand.allBlocks.add(Material.PINK_WOOL);
        BlockCommand.allBlocks.add(Material.GRAY_WOOL);
        BlockCommand.allBlocks.add(Material.LIGHT_GRAY_WOOL);
        BlockCommand.allBlocks.add(Material.CYAN_WOOL);
        BlockCommand.allBlocks.add(Material.PURPLE_WOOL);
        BlockCommand.allBlocks.add(Material.BLUE_WOOL);
        BlockCommand.allBlocks.add(Material.BROWN_WOOL);
        BlockCommand.allBlocks.add(Material.GREEN_WOOL);
        BlockCommand.allBlocks.add(Material.RED_WOOL);
        BlockCommand.allBlocks.add(Material.BLACK_WOOL);
        BlockCommand.allBlocks.add(Material.DANDELION);
        BlockCommand.allBlocks.add(Material.POPPY);
        BlockCommand.allBlocks.add(Material.BLUE_ORCHID);
        BlockCommand.allBlocks.add(Material.ALLIUM);
        BlockCommand.allBlocks.add(Material.AZURE_BLUET);
        BlockCommand.allBlocks.add(Material.RED_TULIP);
        BlockCommand.allBlocks.add(Material.WHITE_TULIP);
        BlockCommand.allBlocks.add(Material.PINK_TULIP);
        BlockCommand.allBlocks.add(Material.CORNFLOWER);
        BlockCommand.allBlocks.add(Material.LILY_OF_THE_VALLEY);
        BlockCommand.allBlocks.add(Material.BROWN_MUSHROOM);
        BlockCommand.allBlocks.add(Material.RED_MUSHROOM);
        BlockCommand.allBlocks.add(Material.IRON_BLOCK);
        BlockCommand.allBlocks.add(Material.LAPIS_BLOCK);
        BlockCommand.allBlocks.add(Material.GOLD_BLOCK);
        BlockCommand.allBlocks.add(Material.OAK_SLAB);
        BlockCommand.allBlocks.add(Material.SPRUCE_SLAB);
        BlockCommand.allBlocks.add(Material.BIRCH_SLAB);
        BlockCommand.allBlocks.add(Material.JUNGLE_SLAB);
        BlockCommand.allBlocks.add(Material.ACACIA_SLAB);
        BlockCommand.allBlocks.add(Material.DARK_OAK_SLAB);
        BlockCommand.allBlocks.add(Material.DRIED_KELP_BLOCK);
        BlockCommand.allBlocks.add(Material.DIORITE_SLAB);
        BlockCommand.allBlocks.add(Material.POLISHED_ANDESITE_SLAB);
        BlockCommand.allBlocks.add(Material.ANDESITE_SLAB);
        BlockCommand.allBlocks.add(Material.GRANITE_SLAB);
        BlockCommand.allBlocks.add(Material.COBBLESTONE_SLAB);
        BlockCommand.allBlocks.add(Material.SMOOTH_QUARTZ_SLAB);
        BlockCommand.allBlocks.add(Material.SMOOTH_SANDSTONE_SLAB);
        BlockCommand.allBlocks.add(Material.POLISHED_DIORITE_SLAB);
        BlockCommand.allBlocks.add(Material.POLISHED_GRANITE_SLAB);
        BlockCommand.allBlocks.add(Material.DIORITE_STAIRS);
        BlockCommand.allBlocks.add(Material.POLISHED_ANDESITE_STAIRS);
        BlockCommand.allBlocks.add(Material.ANDESITE_STAIRS);
        BlockCommand.allBlocks.add(Material.GRANITE_STAIRS);
        BlockCommand.allBlocks.add(Material.SMOOTH_QUARTZ_STAIRS);
        BlockCommand.allBlocks.add(Material.SMOOTH_SANDSTONE_STAIRS);
        BlockCommand.allBlocks.add(Material.STONE_STAIRS);
        BlockCommand.allBlocks.add(Material.SMOOTH_STONE);
        BlockCommand.allBlocks.add(Material.TNT);
        BlockCommand.allBlocks.add(Material.BOOKSHELF);
        BlockCommand.allBlocks.add(Material.OBSIDIAN);
        BlockCommand.allBlocks.add(Material.OAK_STAIRS);
        BlockCommand.allBlocks.add(Material.SPRUCE_STAIRS);
        BlockCommand.allBlocks.add(Material.BIRCH_STAIRS);
        BlockCommand.allBlocks.add(Material.JUNGLE_STAIRS);
        BlockCommand.allBlocks.add(Material.ACACIA_STAIRS);
        BlockCommand.allBlocks.add(Material.DARK_OAK_STAIRS);
        BlockCommand.allBlocks.add(Material.CHEST);
        BlockCommand.allBlocks.add(Material.DIAMOND_ORE);
        BlockCommand.allBlocks.add(Material.CRAFTING_TABLE);
        BlockCommand.allBlocks.add(Material.FARMLAND);
        BlockCommand.allBlocks.add(Material.FURNACE);
        BlockCommand.allBlocks.add(Material.REDSTONE_ORE);
        BlockCommand.allBlocks.add(Material.SNOW_BLOCK);
        BlockCommand.allBlocks.add(Material.ICE);
        BlockCommand.allBlocks.add(Material.CACTUS);
        BlockCommand.allBlocks.add(Material.CLAY);
        BlockCommand.allBlocks.add(Material.JUKEBOX);
        BlockCommand.allBlocks.add(Material.CARVED_PUMPKIN);
        BlockCommand.allBlocks.add(Material.NETHERRACK);
        BlockCommand.allBlocks.add(Material.SOUL_SAND);
        BlockCommand.allBlocks.add(Material.GLOWSTONE);
        BlockCommand.allBlocks.add(Material.OAK_TRAPDOOR);
        BlockCommand.allBlocks.add(Material.SPRUCE_TRAPDOOR);
        BlockCommand.allBlocks.add(Material.BIRCH_TRAPDOOR);
        BlockCommand.allBlocks.add(Material.JUNGLE_TRAPDOOR);
        BlockCommand.allBlocks.add(Material.ACACIA_TRAPDOOR);
        BlockCommand.allBlocks.add(Material.DARK_OAK_TRAPDOOR);
        BlockCommand.allBlocks.add(Material.BROWN_MUSHROOM_BLOCK);
        BlockCommand.allBlocks.add(Material.MELON);
        BlockCommand.allBlocks.add(Material.ANVIL);
        BlockCommand.allBlocks.add(Material.NETHER_QUARTZ_ORE);
        BlockCommand.allBlocks.add(Material.REDSTONE_BLOCK);
        BlockCommand.allBlocks.add(Material.HOPPER);
        BlockCommand.allBlocks.add(Material.HAY_BLOCK);
        BlockCommand.allBlocks.add(Material.WHITE_STAINED_GLASS);
        BlockCommand.allBlocks.add(Material.ORANGE_STAINED_GLASS);
        BlockCommand.allBlocks.add(Material.MAGENTA_STAINED_GLASS);
        BlockCommand.allBlocks.add(Material.LIGHT_BLUE_STAINED_GLASS);
        BlockCommand.allBlocks.add(Material.YELLOW_STAINED_GLASS);
        BlockCommand.allBlocks.add(Material.LIME_STAINED_GLASS);
        BlockCommand.allBlocks.add(Material.PINK_STAINED_GLASS);
        BlockCommand.allBlocks.add(Material.GRAY_STAINED_GLASS);
        BlockCommand.allBlocks.add(Material.LIGHT_GRAY_STAINED_GLASS);
        BlockCommand.allBlocks.add(Material.CYAN_STAINED_GLASS);
        BlockCommand.allBlocks.add(Material.PURPLE_STAINED_GLASS);
        BlockCommand.allBlocks.add(Material.BLUE_STAINED_GLASS);
        BlockCommand.allBlocks.add(Material.BROWN_STAINED_GLASS);
        BlockCommand.allBlocks.add(Material.GREEN_STAINED_GLASS);
        BlockCommand.allBlocks.add(Material.RED_STAINED_GLASS);
        BlockCommand.allBlocks.add(Material.BLACK_STAINED_GLASS);
        BlockCommand.allBlocks.add(Material.MAGMA_BLOCK);
        BlockCommand.allBlocks.add(Material.WHITE_CONCRETE);
        BlockCommand.allBlocks.add(Material.ORANGE_CONCRETE);
        BlockCommand.allBlocks.add(Material.MAGENTA_CONCRETE);
        BlockCommand.allBlocks.add(Material.LIGHT_BLUE_CONCRETE);
        BlockCommand.allBlocks.add(Material.YELLOW_CONCRETE);
        BlockCommand.allBlocks.add(Material.LIME_CONCRETE);
        BlockCommand.allBlocks.add(Material.PINK_CONCRETE);
        BlockCommand.allBlocks.add(Material.GRAY_CONCRETE);
        BlockCommand.allBlocks.add(Material.LIGHT_GRAY_CONCRETE);
        BlockCommand.allBlocks.add(Material.CYAN_CONCRETE);
        BlockCommand.allBlocks.add(Material.PURPLE_CONCRETE);
        BlockCommand.allBlocks.add(Material.BLUE_CONCRETE);
        BlockCommand.allBlocks.add(Material.BROWN_CONCRETE);
        BlockCommand.allBlocks.add(Material.GREEN_CONCRETE);
        BlockCommand.allBlocks.add(Material.RED_CONCRETE);
        BlockCommand.allBlocks.add(Material.BLACK_CONCRETE);
        BlockCommand.allBlocks.add(Material.WHITE_CONCRETE_POWDER);
        BlockCommand.allBlocks.add(Material.ORANGE_CONCRETE_POWDER);
        BlockCommand.allBlocks.add(Material.MAGENTA_CONCRETE_POWDER);
        BlockCommand.allBlocks.add(Material.LIGHT_BLUE_CONCRETE_POWDER);
        BlockCommand.allBlocks.add(Material.YELLOW_CONCRETE_POWDER);
        BlockCommand.allBlocks.add(Material.LIME_CONCRETE_POWDER);
        BlockCommand.allBlocks.add(Material.PINK_CONCRETE_POWDER);
        BlockCommand.allBlocks.add(Material.GRAY_CONCRETE_POWDER);
        BlockCommand.allBlocks.add(Material.LIGHT_GRAY_CONCRETE_POWDER);
        BlockCommand.allBlocks.add(Material.CYAN_CONCRETE_POWDER);
        BlockCommand.allBlocks.add(Material.PURPLE_CONCRETE_POWDER);
        BlockCommand.allBlocks.add(Material.BLUE_CONCRETE_POWDER);
        BlockCommand.allBlocks.add(Material.BROWN_CONCRETE_POWDER);
        BlockCommand.allBlocks.add(Material.GREEN_CONCRETE_POWDER);
        BlockCommand.allBlocks.add(Material.RED_CONCRETE_POWDER);
        BlockCommand.allBlocks.add(Material.BLACK_CONCRETE_POWDER);
        BlockCommand.allBlocks.add(Material.POLISHED_GRANITE_STAIRS);
        BlockCommand.allBlocks.add(Material.POLISHED_DIORITE_STAIRS);
        BlockCommand.allBlocks.add(Material.COBBLESTONE_STAIRS);
        BlockCommand.allBlocks.add(Material.BELL);
        BlockCommand.allBlocks.add(Material.BREWING_STAND);
        BlockCommand.allBlocks.add(Material.RED_BED);
        BlockCommand.allBlocks.add(Material.YELLOW_BED);
        BlockCommand.allBlocks.add(Material.BLUE_BED);
        BlockCommand.allBlocks.add(Material.WHITE_BED);
        BlockCommand.allBlocks.add(Material.BLACK_BED);
        BlockCommand.allBlocks.add(Material.BONE_BLOCK);
        getLogger().info("Blocks successfully added!");
        getLogger().info("BlockShuffle has been enabled");
    }

    @Override
    public void onDisable()
    {
        getLogger().info("Clearing HashSet allBlocks...");
        BlockCommand.allBlocks.clear();
        getLogger().info("allBlocks has been cleared!");
        getLogger().info("BlockShuffle has been disabled");
        instance = null;
    }
}
